# Generated by Django 5.0.14 on 2026-08-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
