# Generated by Django 5.0.14 on 2026-08-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_complaint_is_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
